<a href="https://colab.research.google.com/github/dyjdlopez/mapua_ieemg_decision_science/blob/main/IE151P-S/Module%2001/01_01_intro_to_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01-01: Introduction to Pandas — DataFrames, Series & Basic Analysis

**IE151P-S — Advanced Computer Applications**

Module 1 · Notebook 01-01



**Companion to:** Lesson 1.3 — *Data Types, Cleaning & Transformation*. This notebook builds the pandas foundations you'll need before we get into the actual cleaning techniques from that lesson, in Notebook 01-02.

---

### Learning Objectives

By the end of this notebook, you will be able to:
- Explain what the pandas library is and why it's the core tool for tabular data in Python
- Distinguish `Series` and `DataFrame` objects, and identify their rows, columns, and index
- Use `.describe()` to get a quick statistical summary of a dataset
- Import a real dataset into a DataFrame and select rows and columns using slicing

## 1. Python Data Analysis

<img src="https://commons.wikimedia.org/wiki/Special:FilePath/Pandas_logo.svg" alt="pandas logo" width="360">

*Logo source: [Wikimedia Commons, File:Pandas logo.svg](https://commons.wikimedia.org/wiki/File:Pandas_logo.svg) — freely licensed, used here to identify the open-source pandas project.*

### What is pandas?

**[pandas](https://pandas.pydata.org/docs/)** is an open-source Python library for working with tabular data — the kind of data that naturally sits in rows and columns, like a spreadsheet or a database table. It's built on top of **[NumPy](https://numpy.org/doc/stable/)**, Python's core library for fast numerical computation, and adds the row/column/index structure that raw NumPy arrays don't have on their own.

A useful analogy: think of pandas as Excel's engine, running inside Python. Where a spreadsheet gives you rows, columns, and headers instead of a wall of numbers, pandas gives you the same thing as a Python object you can filter, summarize, and reshape with code — and unlike a spreadsheet, every step is scriptable, repeatable, and works the same way on 10 rows or 10 million.

**A bit of history.** pandas was created in 2008 by Wes McKinney, then a quantitative analyst at AQR Capital Management, who needed a tool as flexible as R's `data.frame` for handling financial time-series data in Python — at the time, Python had good tools for basic data preparation, but very little for structured data analysis. He released the library publicly in 2009, and it has since become the standard tool for tabular data across data science, finance, and research.

**Where does the name come from?** Despite the panda-bear logo, pandas isn't named after the animal. According to McKinney's own account, the name is derived from **panel data** — an econometrics term for multidimensional datasets that track multiple subjects over multiple time periods — combined with a play on "**P**ython **Da**ta A**n**alysi**s**." The panda-bear branding came afterward, because the shortened name happened to evoke it.

Two building blocks do almost everything in pandas:

- **[Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html)** — a single labeled column of data (think: one column of a spreadsheet, plus the row labels next to it)
- **[DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html)** — a full table made of one or more Series that all share the same row labels (the **index**)

Every dataset you'll touch for the rest of this course — the messy patient survey table from Lesson 1.3, and the flight delay data we'll use going forward — gets loaded and manipulated through pandas first, before any cleaning, visualization, or modeling happens. Everything else in this notebook is really just: *how do I build these Series and DataFrames, look inside them, and pull out the piece I need?*

## 2. Worked Example

### 2.1 The Pandas Library

Before anything else, we import pandas. The `as pd` part is just a nickname — it's the near-universal convention, so every pandas tutorial and every piece of code you copy from a colleague will assume `pd` means pandas.

In [ ]:
import pandas as pd

print("pandas version:", pd.__version__)

pandas version: 3.0.2

### 2.2 Primary Data Type: [Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html)

A **[Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html)** is one column of data, plus a label for every row — that row label is called the **[index](https://pandas.pydata.org/docs/reference/api/pandas.Series.index.html)**. Let's build one by hand: defect counts for five production batches.

In [ ]:
defect_counts = pd.Series(
    [3, 5, 2, 4, 6],
    index=['B001', 'B002', 'B003', 'B004', 'B005'],
    name='defect_count'
)

defect_counts

B001    3
B002    5
B003    2
B004    4
B005    6
Name: defect_count, dtype: int64

Notice three things printed above: the **[index](https://pandas.pydata.org/docs/reference/api/pandas.Series.index.html)** (B001–B005, on the left), the **[values](https://pandas.pydata.org/docs/reference/api/pandas.Series.values.html)** (3, 5, 2, 4, 6), and the Series' **name** (`defect_count`). You can pull each of those out on its own:

In [ ]:
print("Index:", defect_counts.index.tolist())
print("Values:", defect_counts.values)

Index: ['B001', 'B002', 'B003', 'B004', 'B005']
Values: [3 5 2 4 6]

### 2.3 Primary Data Type: [DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html)

A **[DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html)** is a full table — several Series stacked side by side, all sharing the same index. The easiest way to build one by hand is from a dictionary, where each key becomes a column name.

In [ ]:
quality_data = {
    'batch_id': ['B001', 'B002', 'B003', 'B004', 'B005'],
    'units_produced': [120, 135, 128, 110, 142],
    'defect_count': [3, 5, 2, 4, 6],
    'inspector': ['Reyes', 'Cruz', 'Reyes', 'Santos', 'Cruz']
}

quality_df = pd.DataFrame(quality_data)
quality_df

  batch_id  units_produced  defect_count inspector
0     B001             120             3     Reyes
1     B002             135             5      Cruz
2     B003             128             2     Reyes
3     B004             110             4    Santos
4     B005             142             6      Cruz

This is a small, **ideal-case** dataset on purpose — five rows, no missing values, nothing messy. We'll compare it against a real, messier dataset in a few cells. For now, let's look at its [`.shape`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html), [`.columns`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html), and [`.index`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.index.html):

In [ ]:
print("Shape (rows, columns):", quality_df.shape)
print("Columns:", quality_df.columns.tolist())
print("Index:", quality_df.index.tolist())

Shape (rows, columns): (5, 4)
Columns: ['batch_id', 'units_produced', 'defect_count', 'inspector']
Index: [0, 1, 2, 3, 4]

### 2.4 Indexing into a DataFrame

There are a few ways to pull data out of a DataFrame, and they answer different questions:

- **Square brackets with one column name** → a single Series
- **Square brackets with a list of column names** → a smaller DataFrame
- **[`.loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)** → select by row/column **label**
- **[`.iloc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)** → select by row/column **position** (like a plain Python list)

In [ ]:
# One column, by name -> a Series
quality_df['units_produced']

0    120
1    135
2    128
3    110
4    142
Name: units_produced, dtype: int64

In [ ]:
# Multiple columns, by name -> a DataFrame
quality_df[['batch_id', 'defect_count']]

  batch_id  defect_count
0     B001             3
1     B002             5
2     B003             2
3     B004             4
4     B005             6

In [ ]:
# One row, by label, using .loc
quality_df.loc[0]

batch_id           B001
units_produced      120
defect_count          3
inspector         Reyes
Name: 0, dtype: object

In [ ]:
# The first two rows, by position, using .iloc
quality_df.iloc[0:2]

  batch_id  units_produced  defect_count inspector
0     B001             120             3     Reyes
1     B002             135             5      Cruz

### 2.5 Basic Analysis: [`.describe()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) — the Ideal Case

`.describe()` gives you a fast statistical summary of every numeric column: how many values there are, their average, spread, and range. Let's run it on our clean toy table first, before we see what it looks like on real (messier) data.

In [ ]:
quality_df.describe()

       units_produced  defect_count
count        5.000000      5.000000
mean       127.000000      4.000000
std         12.529964      1.581139
min        110.000000      2.000000
25%        120.000000      3.000000
50%        128.000000      4.000000
75%        135.000000      5.000000
max        142.000000      6.000000

Every row here means something specific:

| Row | Meaning |
|---|---|
| `count` | how many non-missing values are in that column |
| `mean` | the average |
| `std` | standard deviation — how spread out the values are |
| `min` / `max` | the smallest and largest values |
| `25%` / `50%` / `75%` | the quartiles — `50%` is the median |

Notice `count` is `5` for both numeric columns — no surprises, because this table has no missing values. Keep that number in mind; it won't stay that simple once we load real data.

### 2.6 Importing Data

Hand-built tables are fine for learning the mechanics, but every real dataset gets loaded from a file. We'll use the **Palmer Penguins** dataset — real measurements of penguins from three islands near Palmer Station, Antarctica. [`pd.read_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) can load a CSV directly from a URL, which is the easiest way to work with data in Colab.

**About this dataset.**

<img src="https://commons.wikimedia.org/wiki/Special:FilePath/00_0074_Gentoo_penguin_in_Antarctica.jpg" alt="Gentoo penguin in Antarctica" width="360">

*Photo: [Wikimedia Commons, File:00 0074 Gentoo penguin in Antarctica.jpg](https://commons.wikimedia.org/wiki/File:00_0074_Gentoo_penguin_in_Antarctica.jpg), licensed CC BY-SA 4.0.*

The **Palmer Penguins** dataset contains real body-measurement data for 344 penguins (Adelie, Chinstrap, and Gentoo species) observed on islands in the Palmer Archipelago, Antarctica. It was collected by Dr. Kristen Gorman and the Palmer Station Long Term Ecological Research (LTER) Program, and later packaged for teaching by Allison Horst, Alison Hill, and Kristen Gorman as a modern, ethically-sourced alternative to the (in)famous Iris dataset.

It's a good fit for this notebook for exactly the same reason it's popular in data science courses generally: it's small enough to look at in full, but has just enough real-world messiness — a handful of missing measurements — to make the `.describe()` comparison in Section 2.7 meaningful. The data is released under a CC-0 (public domain) license.

**Citations:**
- Original data: Gorman, K.B., Williams, T.D., & Fraser, W.R. (2014). Ecological sexual dimorphism and environmental variability within a community of Antarctic penguins (genus *Pygoscelis*). *PLoS ONE*, 9(3), e90081. https://doi.org/10.1371/journal.pone.0090081
- Data package: Horst, A.M., Hill, A.P., & Gorman, K.B. (2020). palmerpenguins: Palmer Archipelago (Antarctica) penguin data. R package version 0.1.0. https://allisonhorst.github.io/palmerpenguins/. doi:10.5281/zenodo.3960218

In [ ]:
penguins_url = "https://raw.githubusercontent.com/allisonhorst/palmerpenguins/main/inst/extdata/penguins.csv"
penguins_df = pd.read_csv(penguins_url)

penguins_df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

[`.head()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html) shows the first 5 rows by default — useful for a quick sanity check without printing the whole table. [`.shape`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html) and [`.info()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html) give you the bigger picture: how big the table is, and what type of data lives in each column.

In [ ]:
print("Shape (rows, columns):", penguins_df.shape)
penguins_df.info()

Shape (rows, columns): (344, 8)

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
 7   year               344 non-null    int64
dtypes: float64(4), int64(1), str(3)
memory usage: 21.6 KB

### 2.7 Basic Analysis: [`.describe()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) — the Real Case

Now let's run the same `.describe()` we ran on the toy table — but on real data.

In [ ]:
penguins_df.describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
count,342.000000,342.000000,342.000000,342.000000,344.000000
mean,43.921930,17.151170,200.915205,4201.754386,2008.029070
std,5.459584,1.974793,14.061714,801.954536,0.818356
min,32.100000,13.100000,172.000000,2700.000000,2007.000000
25%,39.225000,15.600000,190.000000,3550.000000,2007.000000
50%,44.450000,17.300000,197.000000,4050.000000,2008.000000
75%,48.500000,18.700000,213.000000,4750.000000,2009.000000
max,59.600000,21.500000,231.000000,6300.000000,2009.000000

Compare this to Section 2.5. The dataset has **344 rows** total (from `.shape` above), but look at the `count` row here — every numeric column shows fewer than 344. That gap between the row count and the `count` in `.describe()` is your first clue that a column has **missing values**.

This is exactly the kind of signal we'll act on in Notebook 01-02, when we get into cleaning techniques properly. For now, just notice: **`.describe()` on real data doesn't just summarize — it can also reveal a problem.**

### 2.8 Selecting Rows and Columns (Slicing)

The same selection patterns from Section 2.4 apply here, just on a bigger, real table.

In [ ]:
# One column, by name -> a Series
penguins_df['species'].head()

0    Adelie
1    Adelie
2    Adelie
3    Adelie
4    Adelie
Name: species, dtype: str

In [ ]:
# Multiple columns, by name -> a DataFrame
penguins_df[['species', 'island', 'body_mass_g']].head()

  species     island  body_mass_g
0  Adelie  Torgersen       3750.0
1  Adelie  Torgersen       3800.0
2  Adelie  Torgersen       3250.0
3  Adelie  Torgersen          NaN
4  Adelie  Torgersen       3450.0

In [ ]:
# First 5 rows, by position, using .iloc
penguins_df.iloc[0:5]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

[`.loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html) also accepts a **condition** instead of a label — this is how you filter rows based on a value, not just a position.

In [ ]:
# Rows where species is "Adelie"
penguins_df.loc[penguins_df['species'] == 'Adelie'].head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

You can combine row and column selection in a single [`.loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html) call: rows first, columns second, separated by a comma.

In [ ]:
# Rows 10 through 20, but only the "island" and "flipper_length_mm" columns
penguins_df.loc[10:20, ['island', 'flipper_length_mm']]

       island  flipper_length_mm
10  Torgersen              186.0
11  Torgersen              180.0
12  Torgersen              182.0
13  Torgersen              191.0
14  Torgersen              198.0
15  Torgersen              185.0
16  Torgersen              195.0
17  Torgersen              197.0
18  Torgersen              184.0
19  Torgersen              194.0
20     Biscoe              174.0

## 3. Guided Practice

Two short exercises. Each has a hint above it — fill in the `# TODO` line(s) and run the cell.

**Exercise 1.** Using [`.loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html), select the **`island`** and **`bill_length_mm`** columns for rows **20 through 30** of `penguins_df`.

*Hint: this is the same pattern as the last cell in Section 2.8 — rows first, then a list of column names, separated by a comma.*

In [ ]:
# TODO: select the 'island' and 'bill_length_mm' columns for rows 20 through 30

**Exercise 2.** Run [`.describe()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.describe.html) on just the **`bill_length_mm`** column (a single Series, not the whole DataFrame). What is the mean bill length, in millimeters?

*Hint: select the single column first — the same way you built a Series in Section 2.4 — then call `.describe()` on it.*

In [ ]:
# TODO: run .describe() on just the 'bill_length_mm' column

## 4. Independent Activity

**New dataset:** `nycflights13` — every flight that departed a New York City airport in 2013 (JFK, LGA, or EWR), over 336,000 rows. This is a real, large dataset with genuine missing data (cancelled flights have no departure or arrival time) — and it's the dataset we'll keep coming back to for the rest of the course.

Your task:

1. Load `flights.csv` (via [`pd.read_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)) from the URL given below into a DataFrame called `flights_df`.
2. Check its shape and use [`.info()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html) to see the column types.
3. Using [`.loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html), select only the rows where `origin` is `'JFK'`, keeping just the `carrier`, `origin`, `dest`, `dep_delay`, and `arr_delay` columns. Store the result in a variable called `jfk_flights`.
4. Run [`.describe()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.describe.html) on `jfk_flights`.

**Expected output:** a summary table for the delay columns, with `count` well under 336,776 — a strong hint about how much missing data cancelled flights leave behind.

**About this dataset.** `nycflights13` contains every flight that departed a New York City airport (JFK, LGA, or EWR) in 2013 — 336,776 flights in total — sourced from the U.S. Bureau of Transportation Statistics and packaged for teaching by Hadley Wickham as part of the tidyverse project. It includes realistic messiness of its own: cancelled flights have no recorded departure or arrival time, which shows up as missing data exactly the way the sentinel-value and null-check techniques from Lesson 1.3 are built to handle.

We're introducing it here because it's the dataset this course will keep returning to — it's large and real enough to support correlation, distribution, regression, and time-series work later on, while still being small enough to load and explore directly from a URL in Colab.

In [ ]:
flights_url = "https://github.com/byuidatascience/data4python4ds/raw/master/data-raw/flights/flights.csv"

# TODO: load flights_url into a DataFrame called flights_df


# TODO: check the shape and run .info()


# TODO: select rows where origin is 'JFK', keeping only
#       carrier, origin, dest, dep_delay, and arr_delay -> store as jfk_flights


# TODO: run .describe() on jfk_flights

## 5. Wrap-Up

- **pandas** turns tabular data into something Python can filter, summarize, and reshape — the same rows/columns/index structure as a spreadsheet, but scriptable
- A **Series** is one labeled column; a **DataFrame** is a table made of Series sharing an index
- `.describe()` is a fast way to see the shape of your numeric data — and a mismatch between `count` and your row total is often the first sign something needs cleaning
- `pd.read_csv()` loads real data directly from a URL, no manual download needed in Colab
- `.loc[]` (by label/condition) and `.iloc[]` (by position) are how you slice out exactly the rows and columns you need

**Next up (Notebook 01-02):** we'll go back to the messy patient survey table from Lesson 1.3 and actually clean it in pandas — deduplication, imputation, standardization, and more — using the exact selection and indexing skills from this notebook.